import "@styles/globals.scss";
import { getUser } from "@lib/Auth/session";

import Nav from "@components/Nav/Nav";
import { ReactNode } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const user = await getUser();

  console.log("user : ", user);

  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{metadata.title}</title>
        <link rel="icon" href="/favicon.ico" />
      </head>

      <body>
        <Nav user={user} />
        {children}
      </body>
    </html>
  );
}
