import "@styles/globals.scss";
import { getSession, getUser } from "@lib/Auth/session";
import Link from "next/link";
import Nav from "@components/Nav/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const user = await getUser();

  console.log("user : ", user);

  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{metadata.title}</title>
        <link rel="icon" href="/favicon.ico" />

        <Nav user={user} />
      </head>

      <body>{children}</body>
    </html>
  );
}
